[package]
authors = ["Jeff Muizelaar <jmuizelaar@mozilla.com>"]
name = "client-storage-rs"
version = "0.1.0"

[dependencies]
euclid = "0.19.5"
gleam = "0.11.0"
glutin = "0.24.0"
libc = "0.2.71"
png = "0.16.3"
core-foundation = "0.9.1"
